config/routes.rb
Smstrails::Application.routes.draw do
  resources :sms

end

app/models/participant.rb
class Participant < ActiveRecord::Base

  validates_presence_of :username, :mobile_number
  validates_uniqueness_of :username, :message => "A participant already exists with the given name"
  validates_uniqueness_of :mobile_number, :message => "Mobile number already registered"
  validates_format_of :username, {
    :with => /^[A-Za-z][0-9A-Za-z_]*$/,
    :message => "must start with a character and can only contain characters or digits",
    :allow_blank => false
  }

  uniquify :token, :length => 4, :chars => 0..9

  has_many :votes
end

app/models/sm.rb
class Sm < ActiveRecord::Base
end

app/models/vote.rb
class Vote < ActiveRecord::Base
  belongs_to :participant
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

app/controllers/sms_controller.rb
require 'twilio-ruby'

class SmsController < ApplicationController
  # POST /sms
  # POST /sms.xml
  def create
    account_sid = 'AC70aee59d3a08b566d66016c127d641b9'
    auth_token = '84a589047447dd7c37e4c0262d888585'
    @client = Twilio::REST::Client.new account_sid, auth_token

    if params[:Body] =~ /^[A-Za-z][0-9A-Za-z_]*$/
      participant = Participant.new(:username => params[:Body], :mobile_number => params[:From])
      if participant.save
        send_sms participant.token, params[:From]
        render :json => participant.to_json
      else
        send_sms "participant username must be unique", params[:From]
        render :json => {}, :status => :unprocessable_entity
      end
    else
      participant = Participant.find_by_token(params[:Body])
      if participant
        participant.votes.create(params[:From])
        send_sms "Thanks! Your Vote for: #{participant.username} has been registered", params[:From]
        render :json => participant.to_json
      else
        send_sms "invalid token", params[:From]
        render :json => {}, :status => :unprocessable_entity
      end
    end
  end

  private
    def send_sms message, from
      @client.account.sms.messages.create(:body => message,
                                          :to => from,
                                          :from => "+18585003433")
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/sms_helper.rb
module SmsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Smstrails</title>
  <%= stylesheet_link_tag :all %>
  <%= javascript_include_tag :defaults %>
  <%= csrf_meta_tag %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/sms/_form.html.erb
<%= form_for(@sm) do |f| %>
  <% if @sm.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@sm.errors.count, "error") %> prohibited this sm from being saved:</h2>

      <ul>
      <% @sm.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <%= f.text_field :body, placeholder: "Message Body" %>
  <%= f.text_field :to, placeholder: "To" %>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/sms/edit.html.erb
<h1>Editing sm</h1>

<%= render 'form' %>

<%= link_to 'Show', @sm %> |
<%= link_to 'Back', sms_path %>

app/views/sms/index.html.erb
<h1>Listing sms</h1>

<table>
  <tr>
    <th></th>
    <th></th>
    <th></th>
  </tr>

<% @sms.each do |sm| %>
  <tr>
    <td><%= link_to 'Show', sm %></td>
    <td><%= link_to 'Edit', edit_sm_path(sm) %></td>
    <td><%= link_to 'Destroy', sm, :confirm => 'Are you sure?', :method => :delete %></td>
  </tr>
<% end %>
</table>

<br />

<%= link_to 'New Sm', new_sm_path %>

app/views/sms/new.html.erb
<h1>New sm</h1>

<%= render 'form' %>
<%= link_to 'Back', sms_path %>

app/views/sms/show.html.erb
<p id="notice"><%= notice %></p>


<%= link_to 'Edit', edit_sm_path(@sm) %> |
<%= link_to 'Back', sms_path %>